#!/usr/bin/env bash

# harsh op - alone_support

# Copyright (C) 2021-2022 harshVenom

#

# This file is a part of < https://github.com/Musicharshi/musicharshi/ >

# PLease read the GNU Affero General Public License in <https://github.com/Musicharshi/musicharshi/LICENSE/>.

if [ -d "resources" ]

then

    echo "Current directory Identified.."

else

    apt install git -y

    git clone https://github.com/Musicharshi/musicharshi 

    cd musicharshi

fi

bash resources/startup/termux.sh
